model:
  model_type: const_sde4
  model_name: cond_unet6
  image_size: [352, 640]
  input_keys: ['image', 'cond']
  ckpt_path:
  ignore_keys: [ ]
  only_model: False
  timesteps: 1000
  train_sample: -1
  sampling_timesteps: 20
  loss_type: l2
  objective: pred_KC
  start_dist: normal
  perceptual_weight: 0
  scale_factor: 0.2417
  scale_by_std: True
  default_scale: True
  scale_by_softsign: False
  eps: !!float 1e-4
  weighting_loss: True
  first_stage:
    embed_dim: 3
    lossconfig:
      disc_start: 50001
      kl_weight: 0.000001
      disc_weight: 0.5
      disc_in_channels: 1
    ddconfig:
      double_z: True
      z_channels: 3
      resolution: [ 320, 320 ]
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0
    ckpt_path: '/home/yyf/Workspace/edge_detection/codes/Mask-Conditioned-Latent-Space-Diffusion/checkpoints/first_stage_model-15.pt'
  unet:
    dim: 128
    channels: 3
    out_mul: 1
    dim_mults: [ 1, 2, 4, 4,] # num_down = len(dim_mults)
    cond_in_dim: 3
    cond_dim: 128
    cond_dim_mults: [ 2, 4 ] # num_down = len(cond_dim_mults)
#    window_sizes1: [ [4, 4], [2, 2], [1, 1], [1, 1] ]
#    window_sizes2: [ [4, 4], [2, 2], [1, 1], [1, 1] ]
    window_sizes1: [ [ 8, 8 ], [ 4, 4 ], [ 2, 2 ], [ 1, 1 ] ]
    window_sizes2: [ [ 8, 8 ], [ 4, 4 ], [ 2, 2 ], [ 1, 1 ] ]
    fourier_scale: 16
    cond_pe: False
    num_pos_feats: 128
    cond_feature_size: [80, 80]

data:
  name: edge
  # img_folder: '/home/yyf/Workspace/edge_detection/codes/edges-eval-crisp-edge/results_gt_imgs_backup/BSDS'
  img_folder: '/home/yyf/Workspace/edge_detection/datasets/BIPED/BIPED_few_shot/BIPED_diffusion'
#  mask_folder: "/nfs/data/diffusion_data/bigsecond/xingbang/mask/"
  augment_horizontal_flip: True
  batch_size: 1
  num_workers: 4

trainer:
  gradient_accumulate_every: 10
  lr: !!float 4e-5
  min_lr: !!float 4e-6
  train_num_steps: 200000
  save_and_sample_every: 1000
  log_freq: 100
  results_folder: "/home/yyf/Workspace/edge_detection/codes/Mask-Conditioned-Latent-Space-Diffusion/checkpoints/results_etp_const_sde4_320x320_unet6"
  amp: False
  fp16: False
  resume_milestone: 0
  test_before: True
  ema_update_after_step: 15000
  ema_update_every: 2

sampler:
  batch_size: 8
  sample_num: 3000
  use_ema: True
  save_folder: "/home/zhuchenyang/project/hyx/data/cityscapes/samples_etp_const_sde4_512x1024_unet6_20"
  ckpt_path: "/home/zhuchenyang/project/hyx/data/cityscapes/results_etp_const_sde4_512x1024_unet6/model-20.pt"

# accelerate launch train_cond_ldm.py --cfg configs/edge_detection/cond_const_sde4_unet6.yaml